# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template_gui_v2.ui'
#
# Created: Thu Apr 23 17:38:33 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(556, 449)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        mainWindow.setFont(font)
        mainWindow.setTabPosition(QtGui.QTabWidget.North)
        mainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        mainWindow.setIconSize(QtCore.QSize(16, 16))
        mainWindow.setElideMode(QtCore.Qt.ElideNone)
        self.tabDetection = QtGui.QWidget()
        self.tabDetection.setGeometry(QtCore.QRect(0, 0, 552, 421))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tabDetection.setFont(font)
        self.tabDetection.setObjectName("tabDetection")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabDetection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.boxAlarms = QtGui.QGroupBox(self.tabDetection)
        self.boxAlarms.setObjectName("boxAlarms")
        self.horizontalLayout = QtGui.QHBoxLayout(self.boxAlarms)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showAlarms = QtGui.QTextEdit(self.boxAlarms)
        self.showAlarms.setReadOnly(True)
        self.showAlarms.setObjectName("showAlarms")
        self.horizontalLayout.addWidget(self.showAlarms)
        self.verticalLayout.addWidget(self.boxAlarms)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.boxStatistics = QtGui.QGroupBox(self.tabDetection)
        self.boxStatistics.setObjectName("boxStatistics")
        self.gridLayout = QtGui.QGridLayout(self.boxStatistics)
        self.gridLayout.setObjectName("gridLayout")
        self.labelStatActAlarms = QtGui.QLabel(self.boxStatistics)
        self.labelStatActAlarms.setTextFormat(QtCore.Qt.AutoText)
        self.labelStatActAlarms.setObjectName("labelStatActAlarms")
        self.gridLayout.addWidget(self.labelStatActAlarms, 0, 0, 1, 1)
        self.labelShowRaiseAlarms = QtGui.QLabel(self.boxStatistics)
        self.labelShowRaiseAlarms.setMinimumSize(QtCore.QSize(50, 0))
        self.labelShowRaiseAlarms.setBaseSize(QtCore.QSize(0, 0))
        self.labelShowRaiseAlarms.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelShowRaiseAlarms.setObjectName("labelShowRaiseAlarms")
        self.gridLayout.addWidget(self.labelShowRaiseAlarms, 0, 1, 1, 1)
        self.labelStatTriggAlarms = QtGui.QLabel(self.boxStatistics)
        self.labelStatTriggAlarms.setObjectName("labelStatTriggAlarms")
        self.gridLayout.addWidget(self.labelStatTriggAlarms, 1, 0, 1, 1)
        self.labelShowTriggAlarms = QtGui.QLabel(self.boxStatistics)
        self.labelShowTriggAlarms.setMinimumSize(QtCore.QSize(0, 0))
        self.labelShowTriggAlarms.setBaseSize(QtCore.QSize(0, 0))
        self.labelShowTriggAlarms.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelShowTriggAlarms.setObjectName("labelShowTriggAlarms")
        self.gridLayout.addWidget(self.labelShowTriggAlarms, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.boxStatistics)
        self.boxStatus = QtGui.QGroupBox(self.tabDetection)
        self.boxStatus.setObjectName("boxStatus")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.boxStatus)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelShowStatus = QtGui.QLabel(self.boxStatus)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.labelShowStatus.setFont(font)
        self.labelShowStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelShowStatus.setObjectName("labelShowStatus")
        self.horizontalLayout_2.addWidget(self.labelShowStatus)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addWidget(self.boxStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonClear = QtGui.QPushButton(self.tabDetection)
        self.buttonClear.setObjectName("buttonClear")
        self.horizontalLayout_5.addWidget(self.buttonClear)
        self.buttonQuit = QtGui.QPushButton(self.tabDetection)
        self.buttonQuit.setObjectName("buttonQuit")
        self.horizontalLayout_5.addWidget(self.buttonQuit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        mainWindow.addTab(self.tabDetection, "")
        self.tabPrevention = QtGui.QWidget()
        self.tabPrevention.setGeometry(QtCore.QRect(0, 0, 552, 421))
        self.tabPrevention.setObjectName("tabPrevention")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabPrevention)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boxPreventionMsg = QtGui.QGroupBox(self.tabPrevention)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.boxPreventionMsg.setFont(font)
        self.boxPreventionMsg.setObjectName("boxPreventionMsg")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.boxPreventionMsg)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.showPreventionMsg = QtGui.QTextEdit(self.boxPreventionMsg)
        self.showPreventionMsg.setReadOnly(True)
        self.showPreventionMsg.setObjectName("showPreventionMsg")
        self.horizontalLayout_6.addWidget(self.showPreventionMsg)
        self.verticalLayout_2.addWidget(self.boxPreventionMsg)
        self.boxPreventionCmd = QtGui.QGroupBox(self.tabPrevention)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.boxPreventionCmd.setFont(font)
        self.boxPreventionCmd.setObjectName("boxPreventionCmd")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.boxPreventionCmd)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.showPreventionCmd = QtGui.QTextEdit(self.boxPreventionCmd)
        self.showPreventionCmd.setReadOnly(True)
        self.showPreventionCmd.setObjectName("showPreventionCmd")
        self.horizontalLayout_8.addWidget(self.showPreventionCmd)
        self.verticalLayout_2.addWidget(self.boxPreventionCmd)
        self.boxPrevStatus = QtGui.QGroupBox(self.tabPrevention)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.boxPrevStatus.setFont(font)
        self.boxPrevStatus.setObjectName("boxPrevStatus")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.boxPrevStatus)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.labelShowPrevStatus = QtGui.QLabel(self.boxPrevStatus)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.labelShowPrevStatus.setFont(font)
        self.labelShowPrevStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelShowPrevStatus.setObjectName("labelShowPrevStatus")
        self.horizontalLayout_10.addWidget(self.labelShowPrevStatus)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.boxPrevStatus)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttonClearPrev = QtGui.QPushButton(self.tabPrevention)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonClearPrev.setFont(font)
        self.buttonClearPrev.setObjectName("buttonClearPrev")
        self.horizontalLayout_7.addWidget(self.buttonClearPrev)
        self.buttonQuit2 = QtGui.QPushButton(self.tabPrevention)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonQuit2.setFont(font)
        self.buttonQuit2.setObjectName("buttonQuit2")
        self.horizontalLayout_7.addWidget(self.buttonQuit2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        mainWindow.addTab(self.tabPrevention, "")

        self.retranslateUi(mainWindow)
        mainWindow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "WIDS/WIPS  - Notifier GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.boxAlarms.setTitle(QtGui.QApplication.translate("mainWindow", "Alarms", None, QtGui.QApplication.UnicodeUTF8))
        self.boxStatistics.setTitle(QtGui.QApplication.translate("mainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStatActAlarms.setText(QtGui.QApplication.translate("mainWindow", "Currently raised alarms", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShowRaiseAlarms.setText(QtGui.QApplication.translate("mainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStatTriggAlarms.setText(QtGui.QApplication.translate("mainWindow", "Triggered alarms", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShowTriggAlarms.setText(QtGui.QApplication.translate("mainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.boxStatus.setTitle(QtGui.QApplication.translate("mainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShowStatus.setText(QtGui.QApplication.translate("mainWindow", "No active alarms", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonClear.setText(QtGui.QApplication.translate("mainWindow", "Clear statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonQuit.setText(QtGui.QApplication.translate("mainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        mainWindow.setTabText(mainWindow.indexOf(self.tabDetection), QtGui.QApplication.translate("mainWindow", "Detection information", None, QtGui.QApplication.UnicodeUTF8))
        self.boxPreventionMsg.setTitle(QtGui.QApplication.translate("mainWindow", "Prevention messages", None, QtGui.QApplication.UnicodeUTF8))
        self.boxPreventionCmd.setTitle(QtGui.QApplication.translate("mainWindow", "Prevention commands", None, QtGui.QApplication.UnicodeUTF8))
        self.boxPrevStatus.setTitle(QtGui.QApplication.translate("mainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShowPrevStatus.setText(QtGui.QApplication.translate("mainWindow", "No active prevention actions", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonClearPrev.setText(QtGui.QApplication.translate("mainWindow", "Clear messages", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonQuit2.setText(QtGui.QApplication.translate("mainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        mainWindow.setTabText(mainWindow.indexOf(self.tabPrevention), QtGui.QApplication.translate("mainWindow", "Prevention information", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QTabWidget()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

